name: Deploy

on:
  push:
    tags: "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Replace version in package.json
        run: 'sed -i "s/\"version\": \"0.0.0\"/\"version\": \"${{ github.ref_name }}\"/" package.json'

      - name: Install VSCE
        run: yarn global add @vscode/vsce

      - name: Install dependencies
        run: yarn install

      - name: Package
        run: echo "y" | vsce package

      - name: Publish
        run: echo "y" | vsce publish -p ${{ secrets.VSCE_TOKEN }}
